// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQcS4lflhRfmJTu_1txHsDo1G2o_ZjB4U',
    appId: '1:291907371604:web:a79608628a614fe54b63c1',
    messagingSenderId: '291907371604',
    projectId: 'catatan-d66c9',
    authDomain: 'catatan-d66c9.firebaseapp.com',
    storageBucket: 'catatan-d66c9.appspot.com',
    measurementId: 'G-KCTZLM76XS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxakd5CCE0Pr9uWNj_Izb5eFJzgDqM4_w',
    appId: '1:291907371604:android:d289aefc79b3aeaf4b63c1',
    messagingSenderId: '291907371604',
    projectId: 'catatan-d66c9',
    storageBucket: 'catatan-d66c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDP6ZDxcIRvbtQDKDDwf8jmtYRtKNdNiU',
    appId: '1:291907371604:ios:102a3c3cef515f924b63c1',
    messagingSenderId: '291907371604',
    projectId: 'catatan-d66c9',
    storageBucket: 'catatan-d66c9.appspot.com',
    iosBundleId: 'com.example.catatan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDP6ZDxcIRvbtQDKDDwf8jmtYRtKNdNiU',
    appId: '1:291907371604:ios:102a3c3cef515f924b63c1',
    messagingSenderId: '291907371604',
    projectId: 'catatan-d66c9',
    storageBucket: 'catatan-d66c9.appspot.com',
    iosBundleId: 'com.example.catatan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQcS4lflhRfmJTu_1txHsDo1G2o_ZjB4U',
    appId: '1:291907371604:web:e9e466ae7728a4d84b63c1',
    messagingSenderId: '291907371604',
    projectId: 'catatan-d66c9',
    authDomain: 'catatan-d66c9.firebaseapp.com',
    storageBucket: 'catatan-d66c9.appspot.com',
    measurementId: 'G-869X1F89JL',
  );
}
